// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
  }
}
